salesforce/force-app/main/default/objects/csconta__Frame_Agreement__c/csconta__Frame_Agreement__c.object-meta.xml
<CustomObject>
    <label>Frame Agreement</label>
    <nameField>
        <displayFormat>AGR-{000000}</displayFormat>
        <label>Frame Agreement Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frame Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/force-app/main/default/objects/csconta__Frame_Agreement__c/fields/async_job__c.field-meta.xml
<CustomField>
    <fullName>async_job__c</fullName>
    <description>Id of last asynchronous job that made changes on Frame Agreement</description>
    <label>Asynchronous Job</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce/force-app/main/default/classes/DecomposeAttachmentQueueable.cls
public with sharing class DecomposeAttachmentQueueable implements Queueable {

	List<Object> categorizationData;
	Integer decompositionChunkSize;
	Id prId;
	Id faId;

	public DecomposeAttachmentQueueable(String data, Integer decompositionChunkSize, Id prId, Id faId) {
		this.decompositionChunkSize = decompositionChunkSize;
		this.prId = prId;
		this.faId = faId;
		categorizationData = (List<Object>) Json.deserializeUntyped(data);
	}

	public void execute(QueueableContext context) {

		List<Object> dataChunk = FrameAgreementActivation.sliceList(categorizationData, 0, decompositionChunkSize);
		if (dataChunk.size() > 0) {
			String msg = FrameAgreementActivation.decomposeAttachment(Json.serialize(dataChunk), prId);
			if (msg != 'Success') {
				throw new CustomExceptions.DecomposeAttachmentException(msg);
			}

			List<Object> nextDataChunk = FrameAgreementActivation.sliceList(
				categorizationData,
				decompositionChunkSize,
				categorizationData.size()
			);
			DecomposeAttachmentQueueable decompose = new DecomposeAttachmentQueueable(
				Json.serialize(nextDataChunk),
				decompositionChunkSize,
				prId,
				faId
			);

			ID jobId = System.enqueueJob(decompose);
			csconta__Frame_Agreement__c fa = [
				select id, async_job__c
				from csconta__Frame_Agreement__c
				where id = :faId
			];
			fa.async_job__c = jobId.to15();
			update fa;
		} else {
			String msg = FrameAgreementActivation.updateFAStatus(faId);
			if (msg != 'Success') {
				throw new CustomExceptions.UpdateFAStatusException(msg);
			} else {
				csconta__Frame_Agreement__c fa = [
					select id, async_job__c
					from csconta__Frame_Agreement__c
					where id = :faId
				];
				fa.async_job__c = null;
				update fa;
			}
		}
	}
}