salesforce/force-app/main/default/objects/csconta__Frame_Agreement__c/csconta__Frame_Agreement__c.object-meta.xml
<CustomObject>
    <label>Frame Agreement</label>
    <nameField>
        <displayFormat>AGR-{000000}</displayFormat>
        <label>Frame Agreement Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frame Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/src/objects/fac_settings__c.object
<CustomObject>
<customSettingsType>Hierarchy</customSettingsType>
    <description>Frame Agreement Console settings (FAC settings) control the behaviour of the application. </description>
    <fields>
        <fullName>account_fields__c</fullName>
        <description>Additional fields to be shown in account table while associating them with Frame Agreement</description>
        <inlineHelpText>Name,csfam__Active__c,Type</inlineHelpText>
        <label>Account Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>active_status__c</fullName>
        <description>Used to define which Frame Agreement status value is used for activating Frame Agreement</description>
        <inlineHelpText>Active</inlineHelpText>
        <label>Active Status</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>approval_process_name__c</fullName>
        <description>Name of the approval process which will be invoked as a result of the negotiation</description>
        <inlineHelpText>FA Approval</inlineHelpText>
        <label>Approval Process Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>approved_status__c</fullName>
        <description>Once Frame Agreement is approved we will change the status to this value</description>
        <inlineHelpText>Approved</inlineHelpText>
        <label>Approved Status</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>approvers_revise__c</fullName>
        <description>Allow approver to edit FA while in "Pending" state.</description>
        <label>Approvers revise</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>closed_status__c</fullName>
        <description>Status of Frame Agreement once it becomes closed replaced. E.g. when a new version is activated.</description>
        <inlineHelpText>Closed Replaced</inlineHelpText>
        <label>Closed Status</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>decomposition_chunk_size__c</fullName>
        <description>Number of items we will process on decomposition in one remote action. Used to tweak performance in case of issues with Salesforce limits.</description>
        <label>Decomposition Chunk Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>discount_as_price__c</fullName>
        <description>If selected, negotiated discount will be shown as new price instead of price difference.</description>
        <label>Discount As Price</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>draft_status__c</fullName>
        <description>Used to define which status will be used in Draft state.</description>
        <inlineHelpText>Draft</inlineHelpText>
        <label>Draft Status</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>fa_editable_statuses__c</fullName>
        <description>CSV list of statuses in which editing and negotiation can happen.</description>
        <inlineHelpText>Draft, Requires Approval</inlineHelpText>
        <label>FA Editable Statuses</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>fa_number_prefix__c</fullName>
        <description>Prefix that is going to be assigned to Frame Agreement Number.</description>
        <inlineHelpText>FA_</inlineHelpText>
        <label>FA Number Prefix</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>frame_agreement_fields__c</fullName>
        <description>Additional Frame Agreement fields to show in FAM.</description>
        <inlineHelpText>csconta__agreement_level__c, csconta__Valid_From__c</inlineHelpText>
        <label>Frame Agreement Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>input_minmax_restriction__c</fullName>
        <description>When true prevents user to input value less than 0 and greater than charges original value.</description>
        <label>Negotiate min/max restriction</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>price_item_fields__c</fullName>
        <description>Populate if additional fields should be displayed in Commercial Product lists.</description>
        <label>Price Item Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>product_chunk_size__c</fullName>
        <description>Size of products to be loaded in one remote action.</description>
        <label>Product Chunk Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rcl_fields__c</fullName>
        <description>Additional Rate Card Line fields used for filtering.</description>
        <inlineHelpText>description__c</inlineHelpText>
        <label>RCL Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>requires_approval_status__c</fullName>
        <description>Used to define which Frame Agreement status will be used when approval is required.</description>
        <inlineHelpText>Requires Approval</inlineHelpText>
        <label>Requires Approval Status</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>new_frame_agreement__c</fullName>
        <description>Toggle visibility of "New Frame Agreement" button</description>
        <inlineHelpText>Requires Approval</inlineHelpText>
        <label>Show New Frame Agreement</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>show_volume_fields__c</fullName>
        <description>If selected, additional volume and usage fields will be shown for each Commercial Product</description>
        <label>Show Volume Fields</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>volume_fields_visibility__c</fullName>
        <description>Additional fields to be shown in account table while associating them with Frame Agreement. On the condition that csfam__show_volume_fields__c is set to true: here you can list volume fields you want to show. Fields are respresented with abbreviation (mv,mvp,muc,mucp)</description>
        <inlineHelpText>mv,mvp</inlineHelpText>
        <label>Volume Fields Visibility</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>truncate_product_fields__c</fullName>
        <description>Used to create a nicer UI by truncating long values in custom fields.</description>
        <label>Truncate CP Fields</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>usage_type_fields__c</fullName>
        <description>Additional Usage type fields.</description>
        <inlineHelpText>mv,mvp</inlineHelpText>
        <label>Usage Type Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>active_status_management__c</fullName>
        <description>On threshold breach while negotiating: FAM will automatically change status of FA to requires_approval_status__c. If all charges are within the threshold limits, it will return it back to draft_status__c.</description>
        <label>Active Status Management</label>
        <type>Checkbox</type>
        <defaultValue>true</defaultValue>
    </fields>
    <fields>
        <fullName>standalone_addon_fields__c</fullName>
        <description>CSV of fully qualified field names to be used when showing standalone addons</description>
        <label>Standalone Addon Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>decimal_places__c</fullName>
        <description>Fields containing price will be rounded to maximum this much decimals.</description>
        <label>Decimal Places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dispatcher_service_url__c</fullName>
        <description>Url endpoint of dispatcher service.</description>
        <label>Dispatcher Service Url</label>
        <type>TextArea</type>
    </fields>
    <label>FAC Setting</label>
</CustomObject>

salesforce/force-app/main/default/classes/PostInstallScript.cls
global class PostInstallScript implements InstallHandler {
	public static final String FA_STANDARD_BUTTON_KEY = 'FA-Standard-buttons';
	public static final String FA_RELATED_LISTS_KEY = 'FA-Related-Lists';
	public static final String FA_HEADER_KEY = 'FA-Header';
	public static final String FA_CATEGORIZATION_KEY = 'FA-Categorization';
	public static final String FA_STANDARDPRICEBOOK_KEY = 'FA-StandardPricebook';
	public static final String FA_CUSTOM_BUTTONS_KEY = 'FA-Custom-Buttons';

	global void onInstall(InstallContext context) {
		if (!context.isUpgrade() && context.previousVersion() == null) {
			PostInstallScript.insertJsonDataConfigs();
			PostInstallScript.insertFacSetting(context.organizationId());
		}
	}

	private static csutil__JSON_Data__c populateJsonSetting(String key, String value) {
		return new csutil__JSON_Data__c (name = key, csutil__value__c = value);
	}

	private static csutil__JSON_Data__c populateStandardButtonSetting() {
		String value = '{"Save":["Draft","Requires Approval"],"SubmitForApproval":["Requires Approval"],"Approve":["Pending"],"Reject":["Pending"],"Recall":["Pending"],"Submit":["Approved","Draft"],"DeleteProducts":["Draft","Requires Approval"],"BulkNegotiate":["Draft","Requires Approval"],"AddProducts":["Draft","Requires Approval"],"DeleteOffers":["Draft","Requires Approval"],"BulkNegotiateOffers":["Draft","Requires Approval"],"AddOffers":["Draft","Requires Approval"],"NewVersion":["Active"],"Delta":["*"]}';
		return PostInstallScript.populateJsonSetting(PostInstallScript.FA_STANDARD_BUTTON_KEY, value);
	}

	private static csutil__JSON_Data__c populateRelatedListSetting() {
		String value = '[{"label":"Child FA","object":"csconta__Frame_Agreement__c","fa_lookup":"csconta__master_frame_agreement__c","columns":"Id, csconta__Agreement_Name__c"},{"label":"Pricing Rule Group","object":"cspmb__Pricing_Rule_Group__c","fa_lookup":"csconta__frame_agreement__c","columns":"Id, cspmb__always_applied__c, cspmb__description__c"}]';
		return PostInstallScript.populateJsonSetting(PostInstallScript.FA_RELATED_LISTS_KEY, value);
	}

	private static csutil__JSON_Data__c populateHeaderSetting() {
		String value = '[{"field":"csconta__Agreement_Name__c","readOnly":false,"label":"Agreement name","type":"text","grid":2},{"field":"csconta__Account__c","readOnly":false,"label":"Account","type":"lookup","grid":3,"lookupData":{"columns":["Name","Type"]}},{"field":"csconta__agreement_level__c","readOnly":false,"label":"Agreement Level","type":"picklist","grid":2}]';
		return PostInstallScript.populateJsonSetting(PostInstallScript.FA_HEADER_KEY, value);
	}

	private static List<csutil__JSON_Data__c> populateSettingsWithEmptyValue() {
		return new List<csutil__JSON_Data__c> {
			PostInstallScript.populateJsonSetting(PostInstallScript.FA_CATEGORIZATION_KEY, ''),
			PostInstallScript.populateJsonSetting(PostInstallScript.FA_STANDARDPRICEBOOK_KEY, ''),
			PostInstallScript.populateJsonSetting(PostInstallScript.FA_CUSTOM_BUTTONS_KEY, '')
		};
	}

	private static void insertJsonDataConfigs() {
		List<csutil__JSON_Data__c> jsonDataList = new List<csutil__JSON_Data__c>();
		jsonDataList.add(PostInstallScript.populateStandardButtonSetting());
		jsonDataList.add(PostInstallScript.populateHeaderSetting());
		jsonDataList.add(PostInstallScript.populateRelatedListSetting());
		jsonDataList.addAll(PostInstallScript.populateSettingsWithEmptyValue());

		insert jsonDataList;
	}

	private static void insertFacSetting(Id orgId) {
		Fac_Settings__c facSetting = Fac_Settings__c.getInstance(orgId);
		facSetting.SetupOwnerId = orgId;
		facSetting.account_fields__c = 'Name,Type';
		facSetting.active_status__c = 'Active';
		facSetting.approval_process_name__c = 'FA';
		facSetting.approvers_revise__c = false;
		facSetting.decimal_places__c = 2;
		facSetting.discount_as_price__c = false;
		facSetting.fa_editable_statuses__c = 'Draft, Requires Approval, Approved';
		facSetting.frame_agreement_fields__c = 'Id, csconta__Account__c';
		facSetting.new_frame_agreement__c = true;
		facSetting.product_chunk_size__c = 100;
		facSetting.requires_approval_status__c = 'Requires Approval';
		facSetting.standalone_addon_fields__c = 'Name, Id';
		facSetting.usage_type_fields__c = 'cspmb__unit_of_measure__c';
		facSetting.active_status_management__c = true;
		facSetting.approved_status__c = 'Approved';
		facSetting.closed_status__c = 'Replaced';
		facSetting.decomposition_chunk_size__c = 1000;
		facSetting.draft_status__c = 'Draft';
		facSetting.fa_number_prefix__c = 'FFF';
		facSetting.input_minmax_restriction__c = true;
		facSetting.price_item_fields__c = 'cspmb__Contract_Term__c, cspmb__Is_Active__c';
		facSetting.rcl_fields__c = 'cspmb__Currency_Code__c';
		facSetting.volume_fields_visibility__c = 'mv, mvp';
		facSetting.truncate_product_fields__c = true;
		facSetting.show_volume_fields__c = true;
		facSetting.dispatcher_service_url__c = 'https://cs-messaging-dispatcher-eu-dev.herokuapp.com';

		insert facSetting;
	}
}